steps:
- name: 'gcr.io/cloud-builders/docker'
  args: ['build','-t', 'gcr.io/certain-region-268322/demo:$COMMIT_SHA', '.']
- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'gcr.io/certain-region-268322/demo:$COMMIT_SHA']
- name: 'gcr.io/cloud-builders/gcloud'
  args: ['beta', 'run', 'deploy', 'demo', '--image', 'gcr.io/certain-region-268322/demo:$COMMIT_SHA', '--region', 'us-central1', '--platform', 'managed', '--allow-unauthenticated']
